### ISSUE TITLE
Which directory do the models exist in, it's useless to follow the instructions, I can't find all the models I've already downloaded.

### ISSUE THREAD

**Issue by xxwx1574711709** [GiusTex/ComfyUI-DiffusersImageOutpaint#11]
Which directory do the models exist in, it's useless to follow the instructions, I can't find all the models I've already downloaded.

**Comment by GiusTex** [comment]
The models aren't downloaded automatically, so what did you use to download them?
- a browser? If yes, you can open the download tab and open the folder where they have been downloaded.
- you want to use already existing models? They wont work probably, they aren't in diffusers format, and anyway the extension read only the models in models/diffusion_models, so you can't tell it to use the already downloaded ones used in another folder.

Then you can put the model files in a folder and the controlnet files in another folder, and the 2 folders into comfyui/models/diffusion_models, as shown in the grid.
