### ISSUE TITLE
Change the base model

### ISSUE THREAD

**Issue by epicstar7** [GiusTex/ComfyUI-DiffusersImageOutpaint#12]
Amazing extension for out painting, thanks for that! 

I was wondering what the base SDXL model actually does to the image in this case. The RealVisXL_V5.0_Lightning_fp16 is recommended and I put it in the folder. Then I thought let's try other models, so I placed other models in the folder but same results. Then I completely removed the model from the folder just to check, but the extension still generates images inside comfy. I checked the code but couldn't really find clues what it's really doing for the image generation.

Does this model even do anything? And if so, how do I actually change it to another model?

Thanks!

**Comment by GiusTex** [comment]
> Amazing extension for out painting, thanks for that!

Very happy to hear that!

> I was wondering what the base SDXL model actually does to the image

Controlnet is passed to the model, and toghether they form the generation pipe.

> Then I completely removed the model from the folder just to check, but the extension still generates images

The extension should unload the model after each generation, but maybe it saved it, did you try restarting comfyui without the model?

> how do I actually change it to another model?

- Thanks for asking, cause I noticed the extension is actually forced to use 2 tokenizers and 2 text_encoders (which is default for sdxl and flux, I think, but not for sd1.5 for example), I'll change it today (to use what's in the model folder). For now all sdxl and ~flux~ models should work, but I still have to test it (probably flux won't be so good with its current controlnet model).
- After I'll have updated utils.py, sd1.5 models should work too (having 1 tokenizer and text_encoder, not 2). Sd1.5 + 1.5 controlnet models, of course.
- (I also tried to use confyui clip loader, so we could skip installing tokenizer and text_encoder but didn't yet manage to merge it with filonii's code).
- How to change diffuser model:
You can go to huggingface and search for text2image models, [search link](https://huggingface.co/models?pipeline_tag=text-to-image&sort=trending), then choose a model and download in a folder its unet, tokenizer and text_encoder, finally put that folder in `comfyui/models/diffusion_models`. I should probably write this in the readme. Then in comfyui choose the new model.
This is all theory, sorry, I'm on the phone outside but today I should be able to make some tests, and anyway this is the path I'll follow

**Comment by GiusTex** [comment]
> how do I actually change it to another model?

I'm making some updates on the [test branch](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/tree/Test). Now the model (unet) and controlnet are left, then changing model will be, easier, quicker (and available)

**Comment by epicstar7** [comment]
Thanks so much @GiusTex, can I already test this? I am not sure how this works with installing it on comfy from a test branch.

**Comment by GiusTex** [comment]
Yeah, you can test it, as I wrote in the [updates](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/tree/main?tab=readme-ov-file#updates) part, typing `git checkout Test`, then `git pull`, I tested it in comfyui and only when it worked I created the new branch; you can also go back to main branch later

**Comment by epicstar7** [comment]
I am getting this:
`F:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-DiffusersImageOutpaint>git checkout Test
Switched to branch 'Test'

F:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-DiffusersImageOutpaint>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> Test`

**Comment by GiusTex** [comment]
> Please specify which branch you want to merge with

Try `git pull ComfyUI-DiffusersImageOutpaint Test`

**Comment by GiusTex** [comment]
I updated the [info](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/edit/Test/README.md#change-model-used). Now for the main model just the unet and scheduler are required, and same for the controlnet (except it doesn't need the scheduler)
