### ISSUE TITLE
How can I outpaint from the center outward?

### ISSUE THREAD

**Issue by arso7** [GiusTex/ComfyUI-DiffusersImageOutpaint#15]
No matter what size image I input, it seems like there's no outpainting. Am I doing something wrong?
![2024-10-26 125230](https://github.com/user-attachments/assets/706a197c-bc8b-4e63-a9b0-bce712e3d3a8)

**Comment by arso7** [comment]
> ## For input images has the same picture aspect ratio as target resolution, need a custom resize option from the huggingface repo.
> 
> ## For input image got white edges like in [issue](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/issues/7) , need overlap option to adjust the image to avoid bad results.

Could you explain a bit more? How can I get this custom resize option? Sorry, I'm still quite new to these things, or could you provide some keywords for me to search? Thank you!

**Comment by GiusTex** [comment]
> Could you explain a bit more?

![image](https://github.com/user-attachments/assets/e0aef5d4-39b7-4468-abb8-32719a78d974)

I think he means this part, from the [filonii's huggingface space](https://huggingface.co/spaces/fffiloni/diffusers-image-outpaint), I want to add that as I wrote [here](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/issues/9#issuecomment-2412945916), but now I'm busy with other things

**Comment by KobayakawaSaeSama** [comment]
> ## For input images has the same picture aspect ratio as target resolution, need a custom resize option from the huggingface repo.
> ![image](https://private-user-images.githubusercontent.com/13308350/380503121-0338d972-98b1-41c3-b72a-defe42a61904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzAzNzcsIm5iZiI6MTczMDMzMDA3NywicGF0aCI6Ii8xMzMwODM1MC8zODA1MDMxMjEtMDMzOGQ5NzItOThiMS00MWMzLWI3MmEtZGVmZTQyYTYxOTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIzMTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGM2OWU4ZGMzMzljYjlmN2JmYTM1YzNlODQyZmEyYjVkN2U4Y2FkMTVhMmFhYmUwNzM0MGI0ZDBmMDI4ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DDzf740XGsEqjg0cdmQjxf6HN6iZpnTkJSU8P_R8AoI)
> 
> ## For input image got white edges like in [issue](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/issues/7) , need overlap option to adjust the image to avoid bad results.
> ![image](https://private-user-images.githubusercontent.com/13308350/380504121-901c6f3e-8fb0-4ea1-8d14-da9daf46b515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzAzNzcsIm5iZiI6MTczMDMzMDA3NywicGF0aCI6Ii8xMzMwODM1MC8zODA1MDQxMjEtOTAxYzZmM2UtOGZiMC00ZWExLThkMTQtZGE5ZGFmNDZiNTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIzMTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGIwOTk1ZTdjYmU5YTIxN2YwNGY5NzhiZDA2ZjcxN2I3ODUwNTA1MzQ1YTBjYzhkZjRhYmM5MTYyMjQzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.il16VZkkQyFRFZmdZ5FmacyP-QwAOFhdIvs_1RXeBwg)

Can I please know the pack name for the "outpiant pad image" node from your screenshot? Thanks!!

**Comment by GiusTex** [comment]
> No matter what size image I input, it seems like there's no outpainting. Am I doing something wrong?

Update the extension and the nodes and try again, if you have problems attach here your workflow or a screen of all of it

**Comment by arso7** [comment]
> > No matter what size image I input, it seems like there's no outpainting. Am I doing something wrong?
> 
> @arso7, update the extension and the nodes and try again, if you have problems attach here your workflow or a screen of all of it

Thank you for the update.

**Comment by GiusTex** [comment]
Is it working now?
