### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/dad/ComfyUI/models/diffusion_models/models.

### ISSUE THREAD

**Issue by sea180** [GiusTex/ComfyUI-DiffusersImageOutpaint#16]
I encountered the following messages when executing outpaint in comfyui (ubuntu platform) , 
"
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/dad/ComfyUI/models/diffusion_models/models.
"
it said some files not there, but they were.

**Comment by GiusTex** [comment]
Did you name the model files like in the grid?

**Comment by sea180** [comment]
yes, I did.

GiusTex ***@***.***> 於 2024年10月27日 週日 下午4:40寫道：

**Comment by GiusTex** [comment]
Can you update the extension and follow the [new grid](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#installation) example? It should be more understandable now

**Comment by GiusTex** [comment]
Update the extension and the nodes, follow the [installation](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#installation) which now has a better model files grid, and write here if you still have problems
