### ISSUE TITLE
LoadDiffusersOutpaintModels Validation Error Despite Correct Model Installation

### ISSUE THREAD

**Issue by ayoubaydy** [GiusTex/ComfyUI-DiffusersImageOutpaint#17]
i appreciate the work 
but the workflow its not working for me can you please help :

First Issue issue ifaced :
Getting validation errors with LoadDiffusersOutpaintModels node:
- "Value not in list: controlnet_model: 'controlnet-union-sdxl-1.0' not in []"
- "Value not in list: model: 'RealVisXL_V5.0_Lightning' not in []"

Steps taken:
1. Installed models in correct path: Packages\ComfyUI\models\diffusion_models\
2. Added both RealVisXL_V5.0_Lightning and controlnet-union-sdxl-1.0
3. Followed folder structure from README
4. Renamed text encoder files as specified

Now an Additional error: 
"Can't load tokenizer" error when trying to use EncodeDiffusersOutpaintPrompt node.
EncodeDiffusersOutpaintPrompt
Can't load tokenizer for 'ComfyUI/models/diffusion_models/RealVisXL_V5.0_Lightning'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'ComfyUI/models/diffusion_models/RealVisXL_V5.0_Lightning' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by GiusTex** [comment]
Did you use the Test branch? Try updating the nodes, and if also used the test branch you need [this](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/blob/Test/Diffusers-Outpaint-Workflow.json) workflow, which is also simpler. (How to [update to test branch](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/tree/main?tab=readme-ov-file#updates))

**Comment by ayoubaydy** [comment]
Thank you very much for your assistance! I updated the nodes and the test branch as you suggested. I ended up cloning the entire model repository, which resolved the issue – it turns out that manually downloading and naming the token folder and other folders ..... had caused some files to not work due to naming inconsistencies. Now everything is working smoothly. I really appreciate your help!

**Comment by GiusTex** [comment]
> Thank you very much for your assistance!

You're welcome!

> I ended up cloning the entire model repository

Did you delete/move elsewhere the `text_encoder`s and `tokenizer`s folders (found in the model repository) once downloaded? In the test branch they are not required and you can free up space. If the code doesn't work you can move back the folders, but you shoudn't need them
