### ISSUE TITLE
Sizes ot tensors must match except in dimension 0

### ISSUE THREAD

**Issue by lunatico67** [GiusTex/ComfyUI-DiffusersImageOutpaint#18]
Hi
What am I doing wrong?

![Error_a](https://github.com/user-attachments/assets/20feee21-551a-493a-8510-054d4a6f34ba)
![Error__b](https://github.com/user-attachments/assets/e5bced44-bf79-4a83-b2bc-abaa03e8a671)
![Error_c](https://github.com/user-attachments/assets/e168206b-0113-43ad-a4a9-2cfcb40fb2d5)
![Error__d](https://github.com/user-attachments/assets/79d31cbc-03c3-4b39-9836-f28fd911fcb6)
![Error_e](https://github.com/user-attachments/assets/cd04215f-051c-4c8a-8d6b-7012ed52171d)
![Error__f](https://github.com/user-attachments/assets/a3f49f61-bf9e-4829-834c-e51dd879ab49)

**Comment by lunatico67** [comment]
> I think I'll have to change the grid in the readme, you have to put the diffusion_pytorch_model.fp16.safetensors in another unet folder. So you would have something like this: diffusion_models:

I lot of thanks for your help GiusTex, this step has been overcome.
Now i get a new error, i think is about the model.fp16.safetensors. I have loaded t5xxl_fp16.safetensors and gives this error:
![fp16](https://github.com/user-attachments/assets/374e312b-7b94-41b5-8303-1b1521adc810)

which version of model.fp16.safetensors should I download?
https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/blob/fb2d258b2299e3b89caa9abd02791ab7245722ca/text_encoder/model.fp16.safetensors

https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/text_encoder/model.fp16.safetensors

https://github.com/Guang000/Generative-Dataset-Distillation-Based-on-Diffusion-Model/blob/main/model.fp16.safetensors

**Comment by GiusTex** [comment]
Second one: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/text_encoder/model.fp16.safetensors
I'll add it to the readme again, I thought I added it but I can't find it

**Comment by lunatico67** [comment]
> You can find it, along with the workflow, at the [third point](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#installation) in the installation step

Thanks for the help.
Again, the same error:
You are trying to load the model files of the `variant=fp16, but no such modeling files are available.
![Last1Error](https://github.com/user-attachments/assets/cd78100a-4ba1-43bc-b1d7-a1e4a4a77acf)
![Last-Error](https://github.com/user-attachments/assets/760a3dfd-1472-432a-b5b8-2e75ec0e64b9)

**Comment by GiusTex** [comment]
Update and try it now

**Comment by lunatico67** [comment]
> Update and try it now

Thank you very much for your quick, attentive and excellent help GiusTex.
Now it works but the outpainting result is really bad as you can see in the picture.
The original image was created with the RealVisXL 2 model, there is a huge difference between the beautiful colors of the original image and the lifeless and ugly colors of the outpainting.
I don't know if it is due to the RealVisXL 5 model, the controlnet Union promax model, the combination of both or the outpainting technique but the result is of very bad quality.
It would be interesting to be able to load models other than RealVisXL 5,perhaps it would improve the quality of the result.
![Outpaint-](https://github.com/user-attachments/assets/572cdbf8-04e2-4ec9-9555-ee748d6ee40b)

**Comment by GiusTex** [comment]
> Now it works

Good to hear that

> the outpainting result is really bad

I saw in [another issue](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/issues/9#issue-2587518947) too that sometimes the [huggingface space](https://huggingface.co/spaces/fffiloni/diffusers-image-outpaint) gives better result, so I'm working on adding the new features in comfyui to see if that helps. Try to outpaint the image in the huggingface space in the meantime to see it the new features help.

> It would be interesting to be able to load models other than RealVisXL 5

You can do it following the steps [here](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#change-model-used)

**Comment by lunatico67** [comment]
Thank you very much for your suggestions, I hope you will get better results soon. Thank you for your contribution to ComfyUI.

**Comment by GiusTex** [comment]
I updated the info to [change model](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#change-model-used) (I suggested to check if the are unrequired model files, I suggest you to read it again, sorry)

**Comment by lunatico67** [comment]
> > Thank you very much for your suggestions
> 
> You're welcome!

Thank you, is a pleasure; I love the outpainting.
I have tried the RealVisXL 4.0 and Juggernaut-XL-v9 models and the result is even worse.
It is not a problem of the models.

**Comment by GiusTex** [comment]
> It is not a problem of the models.

Interesting, well at least changing model works.

What about the [huggingface space](https://huggingface.co/spaces/fffiloni/diffusers-image-outpaint)?

**Comment by GiusTex** [comment]
> If you obtain satisfactory results, it would be interesting if you could make a video tutorial

If I get good results I'll update the workflow... do you prefer videos instead of workflows ?

**Comment by GiusTex** [comment]
> even if it is not giving good results yet, I'm sure it will soon

About that, I'm making some tests (with an image given in another issue with round angles), and for some reason in the huggingface space it comes out good
![image](https://github.com/user-attachments/assets/2f683330-69dd-4479-b0f2-b551612271bc)

While locally (in gradio; comfyui si still wip) is blurry... I'll have to see if in comfy the vae gives better result... (usually blurry results are tied to the vae)

![image](https://github.com/user-attachments/assets/59c84b9a-2817-431a-adbd-7404bebaf7de)

**Comment by GiusTex** [comment]
Can you give me your (not outpainted) image? If you want. This way I'll have more samples to test
![image](https://github.com/user-attachments/assets/feda0c97-d348-4dac-8090-80f8f0e7fbbb)

**Comment by lunatico67** [comment]
I can't due to copyright, that's why I put a part of the image.
Now, with the same settings as before, models and image size works once and five times it doesn't, I get this message:
![Errorrrbg](https://github.com/user-attachments/assets/e2463742-9e46-4a87-a615-91b2fe4b5398)

**Comment by GiusTex** [comment]
> I can't due to copyright, that's why I put a part of the image.

Ah, ok fine

> with the same settings [...] I get this message

I'll look into it

**Comment by GiusTex** [comment]
About `Sizes ot tensors must match...`, can you click on "Show Report" and paste here what you have? From `# ComfyUI Error Report` to `## System Information` (you can copy until there, and avoid what follows System Information)

**Comment by lunatico67** [comment]
> About `Sizes ot tensors must match...`, can you click on "Show Report" and paste here what you have? From `# ComfyUI Error Report` to `## System Information` (you can copy until there, and avoid what follows System Information).
> 
> #### Edit:
> Can you also repeat me what models and controlnets did you use, and share a screen of the workflow/the workflow itself?

Hi GiusTex
I have just made six attempts and all have been successful. Tomorrow I will make more attempts and when it goes wrong I will share with you the error with its detail.
Another curious thing that happens is the following:

![DualCLIPLoader](https://github.com/user-attachments/assets/833d2065-c722-4fdc-a20c-34c74bd56be9)

**Comment by GiusTex** [comment]
I don't know about the clip_I thing, maybe you need to refresh the page (by reloading or with the refresh button in comfy), or the dropdown selection only saves the first dropdown option... I dunno
