### ISSUE TITLE
When loading the graph, the following node types were not found: LoadDiffusersOutpaintModels

### ISSUE THREAD

**Issue by AnxietyVendor** [GiusTex/ComfyUI-DiffusersImageOutpaint#20]
<img width="960" alt="企业微信截图_20241122144205" src="https://github.com/user-attachments/assets/6e4ce452-a848-487a-b457-cf9cd6f73f2f">

**Comment by AnxietyVendor** [comment]
Node manager, used , this poped out
Git clone the repo, tried, this poped out

ahhhhhhhhhhhhhhhhhhhhhhhh!

**Comment by GiusTex** [comment]
Have you tried searching it? In the search bar, or adding it manually

**Comment by AnxietyVendor** [comment]
![image](https://github.com/user-atta
![Uploading 企业微信截图_20241125092050.png…]()
chments/assets/9a1b158b-cc54-48c2-8ff9-cc2fb698d9c3)

**Comment by AnxietyVendor** [comment]
![Uploading 企业微信截图_20241125092050.png…]()

**Comment by AnxietyVendor** [comment]
<img width="631" alt="search" src="https://github.com/user-attachments/assets/34877e3b-a6b8-4853-8d9c-28f9b05e67b6">
Yes I tried, keywords= "Load" and "Load ", not in the results

**Comment by AnxietyVendor** [comment]
<img width="724" alt="drag from pipe" src="https://github.com/user-attachments/assets/d22708a1-a9cb-4f97-82dd-bd56e0b5da6e">

don't know what u mean exactly, I dragged the  diffusers outpaint pipe from the Encode Diffusers Outpaint Prompt node.
There is a diffusers-image-outpaint but not in there

**Comment by AnxietyVendor** [comment]
Funny that class LoadDiffusersOutpaintModels is indeed in the nodes.py

**Comment by GiusTex** [comment]
Does comfyui manager say the extension is in conflict with another one?

**Comment by GiusTex** [comment]
> <img alt="drag from pipe" width="724" src="https://private-user-images.githubusercontent.com/47814652/389335311-d22708a1-a9cb-4f97-82dd-bd56e0b5da6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjk0MDQsIm5iZiI6MTczMjUyOTEwNCwicGF0aCI6Ii80NzgxNDY1Mi8zODkzMzUzMTEtZDIyNzA4YTEtYTljYi00Zjk3LTgyZGQtYmQ1NmUwYjVkYTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEwMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5N2U5MDEwZTdhMDlhODRlMGNjNTMwMDU0ZmFjNGFmNGFiNzljZWM1YWYzYzM3Y2E2MjgzNTA2YmY2YTY4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DY43YwNs0Rvq1rk45oEk6mTaZe8BAfA3v1Sos-M1D_E">

in diffusers outpaint, last option in the right dropdown menu, is there the load diffusers node?

**Comment by AnxietyVendor** [comment]
OK, problem solved after I updated the ComfyUI via git-pull. I thought my ComfyUI was already the latest version because ComfyUI manager said it was, after I used ComfyUI manager to check the update.

**Comment by AnxietyVendor** [comment]
I don't know why I cann't update ComfyUI to the latest v0.3.4 via ComfyUI manager

**Comment by GiusTex** [comment]
> OK, problem solved after I updated the ComfyUI via git-pull

😌

> I don't know why I cann't update ComfyUI [...]] via ComfyUI manager

I don't know too, sometimes even when I updated the extensions they were still updatable later, in the end I created a `.bat` file to update all of them for me and added `git pull` when launching comfyui...
