### ISSUE TITLE
Plaese update for Minimum VRAM: 6 gb

### ISSUE THREAD

**Issue by XavierFang** [GiusTex/ComfyUI-DiffusersImageOutpaint#6]
Please update according to [zmwv823](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/pull/4), because OutOfMemoryError: Allocation on device

**Comment by GiusTex** [comment]
[I already added it](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#update), it's named `sequential_cpu_offload` (which is the right name), it uses 5,8-6 gb vram

**Comment by XavierFang** [comment]
Great ! It works ! I forget to open `sequential_cpu_offload` . Thank you !
