### ISSUE TITLE
The result is not very good ....

### ISSUE THREAD

**Issue by coollofty** [GiusTex/ComfyUI-DiffusersImageOutpaint#7]
![1](https://github.com/user-attachments/assets/a45e7b85-6277-46dd-a420-64d520bc8d85)

![2](https://github.com/user-attachments/assets/15cbb9ac-2ae6-4531-9eee-7f52ce553e57)

Why are the results so different for the same image? I have tried many times and this is already a good result, others are bader.
However, https://huggingface.co/spaces/fffiloni/diffusers-image-outpaint It only ran once here, and the result was great. The picture is the same one.

Other bad result sample:
![3](https://github.com/user-attachments/assets/438fb3ba-1733-401b-b4a6-103fbb9c734e)

**Comment by GiusTex** [comment]
It's strange... can you pass me the image?

**Comment by coollofty** [comment]
![maotouyintg](https://github.com/user-attachments/assets/be42b50c-6726-44ee-bc9d-cbee798e5607)

**Comment by GiusTex** [comment]
The rounded angles don't work well, if you cut a bit the image to remove them it works well again.

![Owl_1](https://github.com/user-attachments/assets/c2ea5589-e74f-4541-b666-3874ecb7f418) 90° angles.

![ComfyUI_temp_sfbic_00003_](https://github.com/user-attachments/assets/083f2845-9b27-4c4d-add5-86b5e36392e9)

![ComfyUI_temp_sfbic_00004_](https://github.com/user-attachments/assets/63b62ba3-683c-4e66-b024-e35c13c002f2)

**Comment by coollofty** [comment]
Well, I see. But why the effect on https://huggingface.co/spaces/fffiloni/diffusers-image-outpaint this website is very good, and the pixels at the edges have not affected it?

**Comment by GiusTex** [comment]
I don't know, maybe he updated the code to check if there are rounded edges, and if yes it cut the image automatically (?)

**Comment by GiusTex** [comment]
You think it would be useful an auto check for rounded corners, and if found, you are warned (or maybe the image is even auto-cropped) ?

**Comment by coollofty** [comment]
Yes, it can be like this, it's just strange. I thought your code was the same as the code with huggingface repo, so the effect should be exactly the same....I will test more other pictures, thanks

**Comment by GiusTex** [comment]
> I thought your code was the same as the code with huggingface repo

It was, around 2 weeks ago, but filonii sometimes updates it, he added for example "Mask overlap (%)", "mask Overlap Top/Overlap Right/Overlap Left/Overlap Bottom", "Resize input image", and I didn't add them...
