### ISSUE TITLE
Why can't the union model be detected?

### ISSUE THREAD

**Issue by zhiyulee3** [GiusTex/ComfyUI-DiffusersImageOutpaint#8]
Does the union model require specifying a folder path?

**Comment by GiusTex** [comment]
Did you put its folder in diffusion_models folder ?

**Comment by zhiyulee3** [comment]
The path where I store the models is ComfyUI\models\diffusion_models\RealVisXL_V5.0_Lightning. The RealVisXL_V5.0_Lightning model can be recognized, but the union model cannot be recognized, even though both models are in the same folder
![QQ截图20241014151444](https://github.com/user-attachments/assets/77a47b5e-7224-4ecc-bc61-2c8dae48397f)

**Comment by GiusTex** [comment]
They cannot be in the same folder, they must be separated

**Comment by zhiyulee3** [comment]
This work, very grateful
