### ISSUE TITLE
Im back ^_^

### ISSUE THREAD

**Issue by coollofty** [GiusTex/ComfyUI-DiffusersImageOutpaint#9]
Source image:
![mg334](https://github.com/user-attachments/assets/ac49718a-b8c5-4bd2-aef4-981be45b599b)

I ran 5 times, and this is already the best result. The other 4 were even worse
![1](https://github.com/user-attachments/assets/c557181d-71d7-46e1-b9c3-3ee3f644fd21)

The results of the Huggingface single test are very good, and I have also tried it three times in a row, all of which are very stable
![2](https://github.com/user-attachments/assets/9f0119a0-e5ed-4ca7-9f49-1528b6f68a06)

**Comment by IuvenisSapiens** [comment]
@coollofty I'm facing the same issue as you described. Here are some additional details: 

> **Good Image Generation Result with Huggingface Space**
>
> ![20241015120302](https://github.com/user-attachments/assets/14a02c54-75c5-4c12-8408-17288da7fbba)`
>
> **Poor Result with ComfyUI**
>
> ![20241015120021](https://github.com/user-attachments/assets/b3fd2c52-f129-4ee2-ba04-97af523fa75e)`

**Comment by GiusTex** [comment]
Thanks for testing, I'll update the extension code based on the huggface space, and see if it will help then

**Comment by GiusTex** [comment]
Update extension and pad image node and try again.
Sorry for the delay.

**Comment by coollofty** [comment]
That's amazing ^_^ I'll test when I'm free
